
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true
			golden_apple_acacia = true
			golden_apple_birch = true
			golden_apple_dark_oak = true
			golden_apple_jungle = true
			golden_apple_oak = true
			golden_apple_spruce = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.cfm]
			stripped_kitchen_sink_light = true
			coffee_table = true
			stripped_kitchen_counter = true
			stripped_bedside_cabinet = true
			desk_cabinet = true
			kitchen_counter = true
			upgraded_gate = true
			crate = true
			stripped_blinds = true
			bedside_cabinet = true
			stripped_cabinet = true
			desk = true
			stripped_kitchen_drawer = true
			kitchen_sink_dark = true
			stripped_desk_cabinet = true
			blinds = true
			stripped_desk = true
			stripped_coffee_table = true
			stripped_crate = true
			table = true
			park_bench = true
			upgraded_fence = true
			stripped_park_bench = true
			cabinet = true
			mail_box = true
			chair = true
			stripped_mail_box = true
			stripped_upgraded_fence = true
			kitchen_drawer = true
			stripped_table = true
			stripped_chair = true
			stripped_kitchen_sink_dark = true
			kitchen_sink_light = true
			stripped_upgraded_gate = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			tiled_door = true
			center_cut_log = true
			pegged_planks = true
			secret_door = true
			smooth_planks = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			beach_door = true
			fine_vertical_planks = true
			diamond_bordered_glass = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			detailed_planks = true
			cobweb_trapdoor = true
			barred_trapdoor = true
			airy_trapdoor = true
			pressed_door = true
			planks_panel = true
			solid_trapdoor = true
			boarded_door = true
			meshed_trapdoor = true
			fancy_trapdoor = true
			paper_door = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			double_herringbone_planks = true
			crated_planks = true
			reinforced_log = true
			classic_windowed_trapdoor = true
			wickered_planks = true
			heavy_trapdoor = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			bundled_log = true
			polished_planks = true
			ornate_bared_glass_pane = true
			wall_torch = true
			glass_door = true
			paneled_door = true
			leafy_trapdoor = true
			pointless_trapdoor = true
			planks_shavings = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			classic_trapdoor = true
			circle_glass = true
			torch = true
			screen_door = true
			crossed_planks = true
			cross_laced_planks = true
			railed_planks = true
			planks_mosaic = true
			circle_glass_pane = true
			versailles_planks = true
			planked_log = true
			woven_glass = true
			woven_trapdoor = true
			gated_door = true
			supported_door = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			tiled_planks = true
			dual_paneled_door = true
			square_glass_pane = true
			overgrown_log = true
			thin_planks = true
			warted_trapdoor = true
			horizontal_lined_glass = true
			natural_planks = true
			brick_bond_planks = true
			bordered_glass_pane = true
			sliding_door = true
			bordered_glass = true
			shack_door = true
			diagonal_planks = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			fortified_door = true
			snowflake_glass = true
			heavy_door = true
			stacked_planks = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true
			damaged_log = true
			nailed_log = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			end_table = true
			stool_chair = true
			stripped_drawer_counter = true
			stripped_counter = true
			covered_desk = true
			stripped_modern_wardrobe = true
			stripped_covered_desk = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_end_table = true
			drawer = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			table = true
			stripped_double_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			stripped_desk = true
			stripped_lower_triple_drawer = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_striped_chair = true
			stripped_stool_chair = true
			cupboard_counter = true
			coffee_table = true
			glass_table = true
			stripped_double_drawer_counter = true
			lower_bookshelf_drawer = true
			stripped_lower_bookshelf_drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			desk = true
			stripped_double_wardrobe = true
			triple_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.handcrafted]
			fancy_bed = true
			dining_bench = true
			drawer = true
			couch = true
			bench = true
			counter = true
			corner_trim = true
			desk = true
			side_table = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			desk = true
			cutting_board = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			kitchen_cabinetry = true
			chair = true
			light_ceiling_fan = true
			table = true
			mail_box = true
			kitchen_storage_cabinet = true
			storage_jar = true
			drawer = true
			kitchen_sink = true
			toilet = true
			crate = true
			dark_ceiling_fan = true
			lattice_fence_gate = true
			bath = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			waffle_door = true
			cottage_door = true
			swamp_door = true
			barn_door = true
			classic_door = true
			beach_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			glass_door = true
			mystic_door = true
			bark_glass_door = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.decorative_blocks]
			beam = true
			seat = true
			palisade = true
			support = true

		[entries.wood_type.another_furniture]
			bench = true
			flower_box = true
			shutter = true
			drawer = true
			shelf = true
			table = true
			chair = true

		[entries.wood_type.hearth_and_home]
			sanded_wood = true
			parquet = true
			vertical_trim = true
			trim = true
			lattice = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.quark]
			vertical_planks = true
			hollow_log = true
			bookshelf = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			stripped_post = true

	[entries.leaves_type]

		[entries.leaves_type.cfm]
			hedge = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

